src/main/java/ch/ludin/pfplaygroundarchetype/beans/TestBean.java
package ch.ludin.pfplaygroundarchetype.beans;

import java.io.Serializable;
import java.util.Date;

import javax.faces.bean.SessionScoped;

import javax.inject.Named;

@SuppressWarnings("serial")
@SessionScoped
@Named("testBean")

public class TestBean implements Serializable {
	public Date getCurrentDate(){
		return new Date();
	}
    public String getTitle(){
    	return "Simple view with a simple bean";
    }

}

src/main/java/ch/ludin/pfplaygroundarchetype/beans/UserBean.java
package ch.ludin.pfplaygroundarchetype.beans;

import java.io.IOException;
import java.io.Serializable;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import ch.ludin.pfplaygroundarchetype.entity.User;
import ch.ludin.pfplaygroundarchetype.entity.UserRole;
import ch.ludin.pfplaygroundarchetype.persistence.DataRepository;


@SuppressWarnings("serial")
@SessionScoped
@Named("userBean")
public class UserBean implements Serializable {

	@Inject
	@DataRepository
	private EntityManager em;

	private String user;
	private String password;

	private FacesContext context;
	private ExternalContext externalContext;
	private HttpServletRequest request;
	private HttpSession session;

	public UserBean() {
		super();
	}

	@PostConstruct
	public void init() {
		context = FacesContext.getCurrentInstance();
		externalContext = context.getExternalContext();
		request = (HttpServletRequest) externalContext.getRequest();
		session = request.getSession(false);

	}

	public void login() {
		context = FacesContext.getCurrentInstance();
		externalContext = context.getExternalContext();
		request = (HttpServletRequest) externalContext.getRequest();
		System.out.println("sdfsa");
		try {
			int idUser = (int) em
					.createQuery(
							"SELECT u.id FROM User u WHERE username = :username")
					.setParameter("username", user).getSingleResult();
			request.login("" + idUser, password);
			user = find(user, password, idUser);
			externalContext.getSessionMap().put("user", user);
			externalContext.redirect("index.html");
			System.out.println("Fertig");
		} catch (Exception e) {
			e.printStackTrace();
			context = FacesContext.getCurrentInstance();
			context.addMessage(null, new FacesMessage(
					FacesMessage.SEVERITY_ERROR, "Access denied", null));
		}

	}

	public String find(String user, String pass, int id) {

		User u = em.find(User.class, id);

		if (user.equals(u.getUsername()) && pass.equals(u.getPassword())) {
			return user;
		}
		return "not authorized";
	}

	public void logout() {

		// Destroys the session for this user.
		if (session != null)
			session.invalidate();

		// Redirects back to the initial page.
		try {
			externalContext.redirect("./");
		} catch (IOException e) {
			e.printStackTrace();
		}

	}

	public void setUser(String user) {
		this.user = user;
	}

	public String getUser() {
		return user;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = getHashMd5(password);
	}

	public String getHashMd5(String clearPass) {
		MessageDigest m;
		try {
			m = MessageDigest.getInstance("MD5");
			m.update(clearPass.getBytes(), 0, clearPass.length());
			return new BigInteger(1, m.digest()).toString(16);
		} catch (NoSuchAlgorithmException e) {
			e.printStackTrace();
		}
		return "";
	}

	public boolean isAdmin() {
		List<UserRole> listUserRole = em
				.createQuery(
						"FROM UserRole ur WHERE ur.user.username = :userName AND ur.role.id = 1")
				.setParameter("userName", user).getResultList();
		if (listUserRole.isEmpty()) {
			return false;
		}
		return true;
	}
}

src/main/java/ch/ludin/pfplaygroundarchetype/entity/Role.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ch.ludin.pfplaygroundarchetype.entity;

import java.io.Serializable;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;


@Entity
@Table(name = "roles")
public class Role implements Serializable {
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Basic(optional = false)
	@Column(name = "id_role")
	private Integer id;
	@Column(name = "role")
	private String role;
	@Column(name = "bemerkung")
	private String bemerkung;


	public Role() {
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getRole() {
		return role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Override
	public String toString() {
		return "Role [id=" + id + "]";
	}

	public String getBemerkung() {
		return bemerkung;
	}
	
	public void setBemerkung(String bemerkung) {
		this.bemerkung = bemerkung;
	}
}

src/main/java/ch/ludin/pfplaygroundarchetype/entity/User.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ch.ludin.pfplaygroundarchetype.entity;

import java.io.Serializable;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "jusers")
public class User implements Serializable {
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Basic(optional = false)
	@Column(name = "id_juser")
	private int id;
	@Column(name = "username")
	private String username;
	@Column(name = "password")
	private String password;

	public User() {
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public int getId() {
		return id;
	}

	public void setId(int id_user) {
		this.id = id_user;
	}

}

src/main/java/ch/ludin/pfplaygroundarchetype/controller/RoleController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ch.ludin.pfplaygroundarchetype.controller;

import java.io.Serializable;
import java.util.List;

import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;
import javax.persistence.EntityTransaction;

import ch.ludin.pfplaygroundarchetype.entity.Role;
import ch.ludin.pfplaygroundarchetype.entity.User;
import ch.ludin.pfplaygroundarchetype.entity.UserRole;
import ch.ludin.pfplaygroundarchetype.persistence.DataRepository;



@Named("roleController")
@SessionScoped
public class RoleController extends AbstractController<Role> implements Serializable {
	
	private static final long serialVersionUID = 1L;

	@Inject
	@DataRepository
	private EntityManager em;


	public RoleController(){
		super(Role.class);
	}
	
	public void deleteRole() {
		EntityTransaction tx = em.getTransaction();
		@SuppressWarnings("unchecked")
		List<UserRole> lustUserRole = em
				.createQuery("FROM UserRole ur WHERE ur.role.id =:idRole")
				.setParameter("idRole", getSelectedRecord().getId()).getResultList();
		for (UserRole ur : lustUserRole) {
			tx.begin();
			em.remove(ur);
			tx.commit();
		}
		tx.begin();
		em.remove(getSelectedRecord());
		tx.commit();

	}

	
	//@TestAnnotation
	public void test() {
		printFacesMessage("Hello", "this is a test by Dani");
	}
}

src/main/java/ch/ludin/pfplaygroundarchetype/controller/UserController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ch.ludin.pfplaygroundarchetype.controller;

import java.io.Serializable;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;
import javax.persistence.EntityTransaction;

import ch.ludin.pfplaygroundarchetype.beans.UserBean;
import ch.ludin.pfplaygroundarchetype.entity.Role;
import ch.ludin.pfplaygroundarchetype.entity.User;
import ch.ludin.pfplaygroundarchetype.entity.UserRole;
import ch.ludin.pfplaygroundarchetype.persistence.DataRepository;



@SuppressWarnings("serial")
@Named("userController")
@SessionScoped
public class UserController implements Serializable {

	@Inject
	@DataRepository
	private EntityManager em;

	private String controlPassword;
	private String password;

	@Inject
	UserBean userbean;

	private User selectedUser;
	private boolean isAdmin = false;

	@PostConstruct
	void init() {

		System.out.println("init User");
		selectedUser = new User();
		password = "";
		controlPassword = "1";
		isAdmin = false;
	}

	@SuppressWarnings("unchecked")
	public void updateUser() {
		
		if (password.equals(controlPassword)) {
			selectedUser.setPassword(password);
			selectedUser.setPassword(userbean.getHashMd5(selectedUser
					.getPassword()));
		} 
		EntityTransaction tx = em.getTransaction();
		tx.begin();
		em.merge(selectedUser);
		tx.commit();

		if (isAdmin) {
			UserRole userrole = new UserRole();
			userrole.setUser(selectedUser);
			userrole.setRole(em.find(Role.class, 1));
			tx.begin();
			em.merge(userrole);
			tx.commit();
		} else if (selectedUser.getId() != 0) {
			List<UserRole> listUserRole = em
					.createQuery(
							"FROM UserRole ur WHERE ur.user.id = :idUser AND ur.role.id = 1")
					.setParameter("idUser", selectedUser.getId())
					.getResultList();
			for (UserRole ur : listUserRole) {
				tx.begin();
				em.remove(ur);
				tx.commit();
			}
		}
		selectedUser = new User();
		password = "";
		controlPassword = "1";
		isAdmin = false;
	}

	public void deleteUser() {
		EntityTransaction tx = em.getTransaction();
		@SuppressWarnings("unchecked")
		List<UserRole> lustUserRole = em
				.createQuery("FROM UserRole ur WHERE ur.user.id =:idUser")
				.setParameter("idUser", selectedUser.getId()).getResultList();
		for (UserRole ur : lustUserRole) {
			tx.begin();
			em.remove(ur);
			tx.commit();
		}
		tx.begin();
		em.remove(selectedUser);
		tx.commit();

		selectedUser = new User();
		password = "";
		controlPassword = "1";
		isAdmin = false;
	}

	public void addUser() {
		password = "";
		controlPassword = "";
		isAdmin = false;
		selectedUser = new User();
	}

	public void cancel() {
		selectedUser = new User();
		controlPassword = "";
		password = "1";
	}

	public void updatePassword() {
		if (password == controlPassword) {
			selectedUser.setPassword(password);
		}
	}

	// GETTER & SETTER

	public List<User> getUserlist() {
		return em.createQuery("FROM User u").getResultList();
	}

	public User getSelectedUser() {
		return selectedUser;
	}

	public void setSelectedUser(User selectedUser) {
		this.selectedUser = selectedUser;
	}

	public boolean getAdmin() {
		if (selectedUser != null) {
			List<UserRole> listUserRole = em
					.createQuery(
							"FROM UserRole ur WHERE ur.user.id = :idUser AND ur.role.id = 1")
					.setParameter("idUser", selectedUser.getId())
					.getResultList();

			if (!listUserRole.isEmpty()) {
				return true;
			}
		}
		return false;
	}

	public void setAdmin(boolean isAdmin) {
		this.isAdmin = isAdmin;
	}

	public String getControlPassword() {
		return controlPassword;
	}

	public void setControlPassword(String controlPassword) {
		this.controlPassword = controlPassword;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}

src/main/webapp/pages/page1.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	template="/templates/template.xhtml">

	<ui:define name="metadata">
	</ui:define>
	<ui:define name="content">

		<h3>
			<h:outputText value="#{testBean.title}">
			</h:outputText>
		</h3>
		
		<h:outputText value="#{testBean.currentDate}">
			<f:convertDateTime dateStyle="full" timeZone="EST" type="date" />
		</h:outputText>

	</ui:define>
</ui:composition>

src/main/webapp/pages/page2.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	template="/templates/template.xhtml">

	<ui:define name="metadata">
	</ui:define>
	<ui:define name="content">

		<h3>
			<h:outputText value="#{employeeBean.title}">
			</h:outputText>
		</h3>



		<p:dataTable value="#{employeeBean.employees}"
			var="employee">
			<p:column>
				<f:facet name="header">
					<h:outputText value="Employee ID"></h:outputText>
				</f:facet>
				<h:outputText value="#{employee.employeeId}"></h:outputText>
			</p:column>
			<p:column>
				<f:facet name="header">
					<h:outputText value="Employee Name"></h:outputText>
				</f:facet>
				<h:outputText value="#{employee.employeeName}"></h:outputText>
			</p:column>
		</p:dataTable>


	</ui:define>
</ui:composition>

src/main/webapp/pages/page3.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core">

<h:head>
	<title>JSF</title>
	<meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
	<h:outputStylesheet library="awesome" name="css/font-awesome.css" />
</h:head>


<h:body>

	<p:growl id="message" life="3000" />

	<p:layout id="mainLayout" fullPage="true">

		<p:layoutUnit position="north" header="Messages">
			<h:form>
				<p:commandButton value="Growl" icon="fa fa-arrow-circle-right"
					action="inputvalidationGrowl?faces-redirect=true" ajax="false" />
			</h:form>
		</p:layoutUnit>
		<p:layoutUnit position="center">
			<h:form>
				<h:panelGroup id="panel">
					<p:panelGrid columns="4" styleClass="ui-noborder">
						<h:outputLabel for="name" value="Name:" style="font-weight:bold" />
						<p:inputText id="name" value="#{text}" required="true"
							label="Name" />
						<p:message for="name" />
						<h:outputText value="#{text}" />

						<h:outputLabel for="textonly" value="text only:"
							style="font-weight:bold" />
						<p:inputText id="textonly" value="#{textonlyRegex}"
							required="true" label="text only" requiredMessage="is text only!"
							validatorMessage="is text only!">
							<f:validateRegex pattern="^[a-zA-Z]+$" for="textonly" />
						</p:inputText>
						<p:message for="textonly" />
						<h:outputText value="#{textonlyRegex}" />

						<h:outputLabel for="integer" value="integer:"
							style="font-weight:bold" />
						<p:inputText id="integer" value="#{integerRegex}" required="true"
							label="integer" requiredMessage="must be a integer!"
							validatorMessage="must be a integer!">
							<f:validateRegex pattern="^\d+$" for="integer" />
						</p:inputText>
						<p:message for="integer" />
						<h:outputText value="#{integerRegex}" />

						<h:outputLabel for="double" value="double:"
							style="font-weight:bold" />
						<p:inputText id="double" value="#{doubleRegex}" required="true"
							label="double" requiredMessage="must be a double!"
							validatorMessage="must be a double!">
							<f:validateRegex pattern="^\d+(\.)?(\d)?$" for="double" />
						</p:inputText>
						<p:message for="double" />
						<h:outputText value="#{doubleRegex}" />

						<h:outputLabel for="email" value="e-mail:"
							style="font-weight:bold" />
						<p:inputText id="email" value="#{emailRegex}" required="true"
							label="double" requiredMessage="must be an e-mail!"
							validatorMessage="must be an e-mail!">
							<f:validateRegex
								pattern="^([0-9a-zA-Z]([-.\w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-\w]*[0-9a-zA-Z]\.)+[a-zA-Z]{2,9})$"
								for="double" />
						</p:inputText>
						<p:message for="double" />
						<h:outputText value="#{doubleRegex}" />
					</p:panelGrid>
				</h:panelGroup>
				<p:commandButton icon="fa fa-save" value="ajax"
					validateClient="true" update="panel"
					actionListener="#{validationController.save()}" />
			</h:form>
		</p:layoutUnit>
	</p:layout>
</h:body>
</html>

src/main/webapp/pages/role.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	template="../templates/template.xhtml">

	<ui:define name="content">


		<p:dialog id="delDialog" widgetVar="delDialog" header="Löschen"
			closable="false" resizable="false">
			<h:form id="delForm">
				<h:panelGrid columns="1" style="margin: auto;">
					<h:outputText value="Soll die Rolle gelöscht werden?" />
				</h:panelGrid>
				<h:panelGrid columns="2" style="margin: 0 auto;">
					<p:commandButton actionListener="#{roleController.deleteRole()}"
						update=":tableForm" icon="ui-icon-check"
						oncomplete="PF('delDialog').hide();" />
					<p:commandButton update=":tableForm" icon="ui-icon-cancel"
						oncomplete="PF('delDialog').hide();"
						actionListener="#{userController.cancel()}" />
				</h:panelGrid>
			</h:form>
		</p:dialog>

		<p:dialog id="addDialog" widgetVar="addDialog" resizable="false"
			closable="false"
			header="Add user: #{userController.selectedUser.username}">
			<h:form id="addForm">

				<h:panelGrid columns="2">
					<h:outputText value="Username" />
					<p:inputText value="#{userController.selectedUser.username}" />
					<h:outputText value="Password" />
					<p:password value="#{userController.password}">
						<p:ajax event="keyup" update="add" />
					</p:password>
					<h:outputText value="Password repeat" />
					<p:password value="#{userController.controlPassword}">
						<p:ajax event="keyup" update="add" />
					</p:password>
				</h:panelGrid>

				<p:commandButton value="add" id="add"
					actionListener="#{userController.updateUser()}"
					oncomplete="PF('addDialog').hide();"
					disabled="#{userController.password ne userController.controlPassword}"
					update=":tableForm" />
				<p:commandButton value="close" oncomplete="PF('addDialog').hide();"
					actionListener="#{userController.cancel()}" />

			</h:form>
		</p:dialog>

		<p:dialog id="updateDialog" widgetVar="updateDialog" resizable="false"
			closable="false"
			header="Update user: #{userController.selectedUser.username}">
			<h:form id="updateForm">

				<h:panelGrid columns="2">
					<h:outputText value="Username" />
					<p:inputText value="#{userController.selectedUser.username}" />
					<h:outputText value="Admin" />
					<p:selectBooleanCheckbox value="#{userController.admin}"
						disabled="#{userController.selectedUser.id eq 0}" />
				</h:panelGrid>

				<p:commandButton value="update" id="update"
					actionListener="#{userController.updateUser()}"
					oncomplete="PF('updateDialog').hide();" update=":tableForm" />
				<p:commandButton value="close"
					oncomplete="PF('updateDialog').hide();"
					actionListener="#{userController.cancel()}" />

			</h:form>
		</p:dialog>

		<p:dialog id="passDialog" widgetVar="passDialog" resizable="false"
			closable="false"
			header="Update password: #{userController.selectedUser.username}">
			<h:form id="passForm">

				<h:panelGrid columns="2">
					<h:outputText value="Password" />
					<p:password value="#{userController.password}">
						<p:ajax event="keyup" update="updatePass" />
					</p:password>
					<h:outputText value="Password repeat" />
					<p:password value="#{userController.controlPassword}">
						<p:ajax event="keyup" update="updatePass" />
					</p:password>
				</h:panelGrid>

				<p:commandButton value="update" id="updatePass"
					actionListener="#{userController.updateUser()}"
					oncomplete="PF('passDialog').hide();"
					disabled="#{userController.password ne userController.controlPassword}"
					update=":tableForm:userTable" />
				<p:commandButton value="close" oncomplete="PF('passDialog').hide();"
					actionListener="#{userController.cancel()}" />

			</h:form>
		</p:dialog>


		<h:form id="tableForm">

			

			<p:dataTable id="userTable" value="#{roleController.recordList}"
				var="u">
				<p:column>
					<h:outputText value="#{u.role}" />
				</p:column>
				<p:column>
					<h:outputText value="#{u.bemerkung}" />
				</p:column>

				<p:column style="width: 180px;">
					<p:commandButton icon="fa fa-pencil"
						actionListener="#{roleController.setSelectedRecord(u)}"
						oncomplete="PF('updateDialog').show();" update=":updateDialog"
						style="margin-right: 10px;" />
					<p:commandButton icon="fa fa-key"
						actionListener="#{roleController.setSelectedRecord(u)}"
						oncomplete="PF('passDialog').show();" update=":passDialog"
						style="margin-right: 10px;" />
					<p:commandButton icon="fa fa-trash"
						actionListener="#{roleController.setSelectedRecord(u)}"
						oncomplete="PF('delDialog').show();" update=":delDialog" />
				</p:column>
			</p:dataTable>
			<p:column>
				<p:commandButton icon="fa fa-plus-circle"
					actionListener="#{userController.addUser()}"
					oncomplete="PF('addDialog').show();" update=":addDialog" />
			</p:column>
		</h:form>
	</ui:define>
</ui:composition>

src/main/webapp/pages/user.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	template="../templates/template.xhtml">

	<ui:define name="content">


		<p:dialog id="delDialog" widgetVar="delDialog" header="Löschen"
			closable="false" resizable="false">
			<h:form id="delForm">
				<h:panelGrid columns="1" style="margin: auto;">
					<h:outputText value="Soll der User gelöscht werden?" />
				</h:panelGrid>
				<h:panelGrid columns="2" style="margin: 0 auto;">
					<p:commandButton actionListener="#{userController.deleteUser()}"
						update=":tableForm" icon="ui-icon-check"
						oncomplete="PF('delDialog').hide();" />
					<p:commandButton update=":tableForm" icon="ui-icon-cancel"
						oncomplete="PF('delDialog').hide();"
						actionListener="#{userController.cancel()}" />
				</h:panelGrid>
			</h:form>
		</p:dialog>

		<p:dialog id="addDialog" widgetVar="addDialog" resizable="false"
			closable="false"
			header="Add user: #{userController.selectedUser.username}">
			<h:form id="addForm">

				<h:panelGrid columns="2">
					<h:outputText value="Username" />
					<p:inputText value="#{userController.selectedUser.username}" />
					<h:outputText value="Password" />
					<p:password value="#{userController.password}">
						<p:ajax event="keyup" update="add" />
					</p:password>
					<h:outputText value="Password repeat" />
					<p:password value="#{userController.controlPassword}">
						<p:ajax event="keyup" update="add" />
					</p:password>
				</h:panelGrid>

				<p:commandButton value="add" id="add"
					actionListener="#{userController.updateUser()}"
					oncomplete="PF('addDialog').hide();"
					disabled="#{userController.password ne userController.controlPassword}"
					update=":tableForm" />
				<p:commandButton value="close" oncomplete="PF('addDialog').hide();"
					actionListener="#{userController.cancel()}" />

			</h:form>
		</p:dialog>

		<p:dialog id="updateDialog" widgetVar="updateDialog" resizable="false"
			closable="false"
			header="Update user: #{userController.selectedUser.username}">
			<h:form id="updateForm">

				<h:panelGrid columns="2">
					<h:outputText value="Username" />
					<p:inputText value="#{userController.selectedUser.username}" />
					<h:outputText value="Admin" />
					<p:selectBooleanCheckbox value="#{userController.admin}"
						disabled="#{userController.selectedUser.id eq 0}" />
				</h:panelGrid>

				<p:commandButton value="update" id="update"
					actionListener="#{userController.updateUser()}"
					oncomplete="PF('updateDialog').hide();" update=":tableForm" />
				<p:commandButton value="close"
					oncomplete="PF('updateDialog').hide();"
					actionListener="#{userController.cancel()}" />

			</h:form>
		</p:dialog>

		<p:dialog id="passDialog" widgetVar="passDialog" resizable="false"
			closable="false"
			header="Update password: #{userController.selectedUser.username}">
			<h:form id="passForm">

				<h:panelGrid columns="2">
					<h:outputText value="Password" />
					<p:password value="#{userController.password}">
						<p:ajax event="keyup" update="updatePass" />
					</p:password>
					<h:outputText value="Password repeat" />
					<p:password value="#{userController.controlPassword}">
						<p:ajax event="keyup" update="updatePass" />
					</p:password>
				</h:panelGrid>

				<p:commandButton value="update" id="updatePass"
					actionListener="#{userController.updateUser()}"
					oncomplete="PF('passDialog').hide();"
					disabled="#{userController.password ne userController.controlPassword}"
					update=":tableForm:userTable" />
				<p:commandButton value="close" oncomplete="PF('passDialog').hide();"
					actionListener="#{userController.cancel()}" />

			</h:form>
		</p:dialog>


		<h:form id="tableForm">

			

			<p:dataTable id="userTable" value="#{userController.userlist}"
				var="u">
				<p:column>
					<h:outputText value="#{u.username}" />
				</p:column>
				<p:column>
					<h:outputText value="#{u.password}" />
				</p:column>

				<p:column style="width: 180px;">
					<p:commandButton icon="fa fa-pencil"
						actionListener="#{userController.setSelectedUser(u)}"
						oncomplete="PF('updateDialog').show();" update=":updateDialog"
						style="margin-right: 10px;" />
					<p:commandButton icon="fa fa-key"
						actionListener="#{userController.setSelectedUser(u)}"
						oncomplete="PF('passDialog').show();" update=":passDialog"
						style="margin-right: 10px;" />
					<p:commandButton icon="fa fa-trash"
						actionListener="#{userController.setSelectedUser(u)}"
						oncomplete="PF('delDialog').show();" update=":delDialog" />
				</p:column>
			</p:dataTable>
			<p:column>
				<p:commandButton icon="fa fa-plus-circle"
					actionListener="#{userController.addUser()}"
					oncomplete="PF('addDialog').show();" update=":addDialog" />
			</p:column>
		</h:form>
	</ui:define>
</ui:composition>